#+ endpoint: https://query.wikidata.org/sparql

PREFIX wd: <http://www.wikidata.org/entity/>
PREFIX wdt: <http://www.wikidata.org/prop/direct/>
PREFIX wikibase: <http://wikiba.se/ontology#>
PREFIX bd: <http://www.bigdata.com/rdf#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>

SELECT ?person ?personLabel ?birthDate WHERE {
  # Step 1: ?person is an instance of human (Q5)
  ?person wdt:P31 wd:Q5.
  
  # Step 2: Get the birth date of the person
  ?person wdt:P569 ?birthDate.
  
  # Step 3: Filter to only include birth dates in 1966
  FILTER(YEAR(?birthDate) = 1966)

  # Step 4: Get the label (human-readable name) of the person
  SERVICE wikibase:label { bd:serviceParam wikibase:language "en". }
}
